### ISSUE TITLE
Specify a default value

### ISSUE THREAD

**Issue by tjdevries** [sprout42/StarStruct#22]
Sometimes you have an ending of a message, and it's always some value.

So you might want to be able to specify something like

``` python
MyMessage = Message(..., [
  ('ending', 'II', (0, 0))
])
```

**Comment by sprout42** [comment]
Agreed, although I would rather make this a bit more generic to be a "constant" message element where you can specify the name, the format, and then the 3rd element would be the values to place into the element when packing the message.

When packing this field would be ignored since it would just use the pre-populated data.  When unpacking it would validate the data matches the expected values, but then it would not need to be returned.

Perhaps we don't even need the "name" field in this case since it will never be returned in the message data when it is unpacked?

Or would it be preferable to have the data always be unpacked but then compared to the "constant"/"ending" values AND viewable in the unpacked message?

**Comment by tjdevries** [comment]
I think you'd want to still have it around, after all `explicit is better than implicit` :wink:. It would simply doing something like:

``` python
assert MyMessage.pack(**my_dict) == bytes(...)

# or

assert MyMessage.make(**my_dict).ending == b'\x00\x00')

# or

while True:
  read_bytes = read(stream)
  if read_bytes == MyMessage.escape_sequence:
    break
  # process stuff...
```

I think you'd want to keep them around in all the circumstances otherwise it seems like magic.

**Comment by sprout42** [comment]
true... so it should return the constant values in unpack, it would also `assert` that the data was present in the message.

In unpack the data would be automatically packed from the data specified in the constructor.

**Comment by tjdevries** [comment]
I think that would be best.

**Comment by sprout42** [comment]
Added in PR #30
